export * from './advantagesScreen/AdvantagesScreen.tsx'
export * from './contactsScreen/ContactsScreen.tsx'
export * from './feedbackScreen/FeedbackScreen.tsx'
export * from './goodsScreen/GoodsScreen.tsx'
export * from './mainScreen/MainScreen.tsx'
export * from './miniAdvanScreen/MiniAdvanScreen.tsx'
export * from './questionsScreen/QuestionsScreen.tsx'